version: "3.9"
services:
    server:
        container_name: kickbets-server
        build:
            context: .
            dockerfile: Sobczal1.KickBets.Api/Dockerfile
        ports:
          - 8000:80
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "SilneHaslo12345***"
            ACCEPT_EULA: "Y"
    client:
        container_name: kickbets-client
        build:
          context: client-app
          dockerfile: Dockerfile
        ports:
          - 3000:3000
        environment:
          - CHOKIDAR_USEPOLLING=true
            